#include "InputFileTestDatabase.hxx"

#include "material1.hxx"

namespace InputXMLBoundaryTest
{
    std::string constantHeatFlux()
    {
        return {"  <BoundaryConditionTransient> \n"
                "    <HeatFluxTimestep>          \n"
                "      <Index>1</Index>          \n"
                "      <HeatFlux>20</HeatFlux>   \n"
                "    </HeatFluxTimestep>         \n"
                "    <HeatFluxTimestep>          \n"
                "      <Index>2</Index>          \n"
                "      <HeatFlux>20</HeatFlux>   \n"
                "    </HeatFluxTimestep>         \n"
                "    <HeatFluxTimestep>          \n"
                "      <Index>3</Index>          \n"
                "      <HeatFlux>20</HeatFlux>   \n"
                "    </HeatFluxTimestep>         \n"
                "    <HeatFluxTimestep>          \n"
                "      <Index>4</Index>          \n"
                "      <HeatFlux>20</HeatFlux>   \n"
                "    </HeatFluxTimestep>         \n"
                "    <HeatFluxTimestep>          \n"
                "      <Index>5</Index>          \n"
                "      <HeatFlux>20</HeatFlux>   \n"
                "    </HeatFluxTimestep>         \n"
                "  </BoundaryConditionTransient>\n"};
    }

    std::string constantHeatFluxDatabase()
    {
        std::string fileContent{"<InputBoundaryConditionsData>\n"};
        fileContent += "<Name>Comprehensive Natural Model Exterior</Name>\n";
        fileContent += constantHeatFlux();
        fileContent += "</InputBoundaryConditionsData>";
        return fileContent;
    }

    std::string tarpInside()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>		"
                "		<ConvectionTimesteps>"
                "			<TARPTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "			</TARPTimestep>"
                "			<TARPTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "			</TARPTimestep>"
                "			<TARPTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "			</TARPTimestep>"
                "			<TARPTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "			</TARPTimestep>"
                "			<TARPTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "			</TARPTimestep>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string ashraeInside()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">\n"
                "  <Name>Comprehensive Natural Model Exterior</Name>\n"
                "  <BoundaryConditionTransient>\n"
                "		<ConvectionTimesteps>\n"
                "			<ASHRAETimestepInside>\n"
                "				<Index>1</Index>\n"
                "				<Temperature>18</Temperature>\n"
                "				<Humidity>0.2</Humidity>\n"
                "			</ASHRAETimestepInside>\n"
                "			<ASHRAETimestepInside>\n"
                "				<Index>2</Index>\n"
                "				<Temperature>19.8</Temperature>\n"
                "				<Humidity>0.2</Humidity>\n"
                "			</ASHRAETimestepInside>\n"
                "			<ASHRAETimestepInside>\n"
                "				<Index>3</Index>\n"
                "				<Temperature>20</Temperature>\n"
                "				<Humidity>0.3</Humidity>\n"
                "			</ASHRAETimestepInside>\n"
                "			<ASHRAETimestepInside>\n"
                "				<Index>4</Index>\n"
                "				<Temperature>20</Temperature>\n"
                "				<Humidity>0.3</Humidity>\n"
                "			</ASHRAETimestepInside>\n"
                "			<ASHRAETimestepInside>\n"
                "				<Index>5</Index>\n"
                "				<Temperature>18.5</Temperature>\n"
                "				<Humidity>0.3</Humidity>\n"
                "			</ASHRAETimestepInside>\n"
                "		</ConvectionTimesteps>\n"
                "  </BoundaryConditionTransient>\n"
                "</InputBoundaryConditionsData>"};
    }

    std::string ashraeOutside()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<ConvectionTimesteps>"
                "			<ASHRAETimestepOutside>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.23</Humidity>"
                "				<WindSpeed>1.2</WindSpeed>"
                "			</ASHRAETimestepOutside>"
                "			<ASHRAETimestepOutside>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>2.2</WindSpeed>"
                "			</ASHRAETimestepOutside>"
                "			<ASHRAETimestepOutside>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>2.7</WindSpeed>"
                "			</ASHRAETimestepOutside>"
                "			<ASHRAETimestepOutside>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "			</ASHRAETimestepOutside>"
                "			<ASHRAETimestepOutside>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "			</ASHRAETimestepOutside>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string fixedFilmCoefficient()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Fixed Film Coefficient Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<ConvectionTimesteps>"
                "			<FixedConvectionFilmTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<FilmCoefficient>8</FilmCoefficient>"
                "			</FixedConvectionFilmTimestep>"
                "			<FixedConvectionFilmTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<FilmCoefficient>4</FilmCoefficient>"
                "			</FixedConvectionFilmTimestep>"
                "			<FixedConvectionFilmTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<FilmCoefficient>4</FilmCoefficient>"
                "			</FixedConvectionFilmTimestep>"
                "			<FixedConvectionFilmTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<FilmCoefficient>4</FilmCoefficient>"
                "			</FixedConvectionFilmTimestep>"
                "			<FixedConvectionFilmTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<FilmCoefficient>1</FilmCoefficient>"
                "			</FixedConvectionFilmTimestep>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string yazdanianKlems()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<ConvectionTimesteps>"
                "			<YazdanianKlemsTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>1.2</WindSpeed>"
                "				<WindDirection>45</WindDirection>"
                "			</YazdanianKlemsTimestep>"
                "			<YazdanianKlemsTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>2.2</WindSpeed>"
                "				<WindDirection>35</WindDirection>"
                "			</YazdanianKlemsTimestep>"
                "			<YazdanianKlemsTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>2.7</WindSpeed>"
                "				<WindDirection>55</WindDirection>"
                "			</YazdanianKlemsTimestep>"
                "			<YazdanianKlemsTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>115</WindDirection>"
                "			</YazdanianKlemsTimestep>"
                "			<YazdanianKlemsTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>160</WindDirection>"
                "			</YazdanianKlemsTimestep>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string kimura()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<ConvectionTimesteps>"
                "			<KimuraTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>1.2</WindSpeed>"
                "				<WindDirection>220</WindDirection>"
                "			</KimuraTimestep>"
                "			<KimuraTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>2.2</WindSpeed>"
                "				<WindDirection>245</WindDirection>"
                "			</KimuraTimestep>"
                "			<KimuraTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>2.7</WindSpeed>"
                "				<WindDirection>200</WindDirection>"
                "			</KimuraTimestep>"
                "			<KimuraTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>190</WindDirection>"
                "			</KimuraTimestep>"
                "			<KimuraTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>165</WindDirection>"
                "			</KimuraTimestep>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string montazeri()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<ConvectionTimesteps>"
                "			<MontazeriTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>-18</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>1.2</WindSpeed>"
                "				<WindDirection>45</WindDirection>"
                "			</MontazeriTimestep>"
                "			<MontazeriTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>-19.8</Temperature>"
                "				<Humidity>0.2</Humidity>"
                "				<WindSpeed>2.2</WindSpeed>"
                "				<WindDirection>35</WindDirection>"
                "			</MontazeriTimestep>"
                "			<MontazeriTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>2.7</WindSpeed>"
                "				<WindDirection>55</WindDirection>"
                "			</MontazeriTimestep>"
                "			<MontazeriTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>-20</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>115</WindDirection>"
                "			</MontazeriTimestep>"
                "			<MontazeriTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>-18.5</Temperature>"
                "				<Humidity>0.3</Humidity>"
                "				<WindSpeed>3.0</WindSpeed>"
                "				<WindDirection>160</WindDirection>"
                "			</MontazeriTimestep>"
                "		</ConvectionTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string linearizedRadiation()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">\n"
                "  <Name>Fixed Film Coefficient Interior</Name>\n"
                "  <BoundaryConditionTransient>\n"
                "		<RadiationTimesteps>\n"
                "			<FixedRadiationCoefficientTimestep>\n"
                "				<Index>1</Index>\n"
                "				<Temperature>20</Temperature>\n"
                "				<hr>2.3</hr>\n"
                "			</FixedRadiationCoefficientTimestep>\n"
                "			<FixedRadiationCoefficientTimestep>\n"
                "				<Index>2</Index>\n"
                "				<Temperature>21</Temperature>\n"
                "				<hr>2.3</hr>\n"
                "			</FixedRadiationCoefficientTimestep>\n"
                "			<FixedRadiationCoefficientTimestep>\n"
                "				<Index>3</Index>\n"
                "				<Temperature>23</Temperature>\n"
                "				<hr>2.6</hr>\n"
                "			</FixedRadiationCoefficientTimestep>\n"
                "			<FixedRadiationCoefficientTimestep>\n"
                "				<Index>4</Index>\n"
                "				<Temperature>23</Temperature>\n"
                "				<hr>2.4</hr>\n"
                "			</FixedRadiationCoefficientTimestep>\n"
                "			<FixedRadiationCoefficientTimestep>\n"
                "				<Index>5</Index>\n"
                "				<Temperature>23</Temperature>\n"
                "				<hr>2.5</hr>\n"
                "			</FixedRadiationCoefficientTimestep>\n"
                "		</RadiationTimesteps>\n"
                "  </BoundaryConditionTransient>\n"
                "</InputBoundaryConditionsData>"};
    }

    std::string blackBodyRadiation()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Fixed Film Coefficient Interior</Name>"
                "  <BoundaryConditionTransient>"
                "		<RadiationTimesteps>"
                "			<BlackBodyRadiationTimestep>"
                "				<Index>1</Index>"
                "				<Temperature>20</Temperature>"
                "				<Emissivity>0.9</Emissivity>"
                "			</BlackBodyRadiationTimestep>"
                "			<BlackBodyRadiationTimestep>"
                "				<Index>2</Index>"
                "				<Temperature>21</Temperature>"
                "				<Emissivity>0.9</Emissivity>"
                "			</BlackBodyRadiationTimestep>"
                "			<BlackBodyRadiationTimestep>"
                "				<Index>3</Index>"
                "				<Temperature>23</Temperature>"
                "				<Emissivity>0.9</Emissivity>"
                "			</BlackBodyRadiationTimestep>"
                "			<BlackBodyRadiationTimestep>"
                "				<Index>4</Index>"
                "				<Temperature>23</Temperature>"
                "				<Emissivity>0.9</Emissivity>"
                "			</BlackBodyRadiationTimestep>"
                "			<BlackBodyRadiationTimestep>"
                "				<Index>5</Index>"
                "				<Temperature>23</Temperature>"
                "				<Emissivity>0.9</Emissivity>"
                "			</BlackBodyRadiationTimestep>"
                "		</RadiationTimesteps>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string fixedTemperatureAndHumidity()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Fixed Film Coefficient Interior</Name>"
                "  <BoundaryConditionTransient>"
                "		<TemperatureTimestep>"
                "			<Index>1</Index>"
                "			<Temperature>20</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>2</Index>"
                "			<Temperature>21</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>3</Index>"
                "			<Temperature>21</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>4</Index>"
                "			<Temperature>21</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>5</Index>"
                "			<Temperature>21</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>6</Index>"
                "			<Temperature>22</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>7</Index>"
                "			<Temperature>22</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>8</Index>"
                "			<Temperature>23</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>9</Index>"
                "			<Temperature>22</Temperature>"
                "		</TemperatureTimestep>"
                "		<TemperatureTimestep>"
                "			<Index>10</Index>"
                "			<Temperature>20</Temperature>"
                "		</TemperatureTimestep>"
                "		<HumidityTimestep>"
                "			<Index>1</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>2</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>3</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>4</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>5</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>6</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>7</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>8</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>9</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "		<HumidityTimestep>"
                "			<Index>10</Index>"
                "			<Humidity>0</Humidity>"
                "		</HumidityTimestep>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }

    std::string fixedHeatFlux()
    {
        return {"<?xml version=\"1.0\"?>"
                "<InputBoundaryConditionsData xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                "  xsi:noNamespaceSchemaLocation=\"BoundaryConditionsInputFile.xsd\">"
                "  <Name>Comprehensive Natural Model Exterior</Name>"
                "  <BoundaryConditionTransient>"
                "		<HeatFluxTimestep>"
                "			<Index>1</Index>"
                "			<HeatFlux>20</HeatFlux>"
                "		</HeatFluxTimestep>"
                "		<HeatFluxTimestep>"
                "			<Index>2</Index>"
                "			<HeatFlux>20</HeatFlux>"
                "		</HeatFluxTimestep>"
                "		<HeatFluxTimestep>"
                "			<Index>3</Index>"
                "			<HeatFlux>20</HeatFlux>"
                "		</HeatFluxTimestep>"
                "		<HeatFluxTimestep>"
                "			<Index>4</Index>"
                "			<HeatFlux>20</HeatFlux>"
                "		</HeatFluxTimestep>"
                "		<HeatFluxTimestep>"
                "			<Index>5</Index>"
                "			<HeatFlux>20</HeatFlux>"
                "		</HeatFluxTimestep>"
                "  </BoundaryConditionTransient>"
                "</InputBoundaryConditionsData>"};
    }
}   // namespace InputXMLBoundaryTest
