#include "material1.hxx"

namespace TestMaterial
{
    std::string testDatabaseEmptyMoisture()
    {
        std::string fileContent{"<Materials>\n"};
        fileContent += emptyMoisture1();
        fileContent += "</Materials>";
        return fileContent;
    }

    std::string testDatabase()
    {
        std::string fileContent{"<Materials>\n"};
        fileContent += "<Version>1</Version>\n";
        fileContent += material1();
        fileContent += material2();
        fileContent += shade1();
        fileContent += enclosure1();
        fileContent += cavity1();
        fileContent += cavity2();
        fileContent += "</Materials>";
        return fileContent;
    }

    std::string material1()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>26fc05d4-a7aa-43a1-b473-c984caefea5b</UUID>\n"
                "\t\t<Name>Test Material 1</Name>\n"
                "\t\t<Protected>true</Protected>\n"
                "\t\t<Color>0xBAA7A7</Color>\t\t\n"
                "\t\t<Solid>\n"
                "\t\t\t<HygroThermal>\n"
                "\t\t\t\t<BulkDensity>1330.000000</BulkDensity>\n"
                "\t\t\t\t<Porosity>0.500000</Porosity>\n"
                "\t\t\t\t<SpecificHeatCapacityDry>850.000000</SpecificHeatCapacityDry>\n"
                "\t\t\t\t<ThermalConductivityDry>0.870000</ThermalConductivityDry>\n"
                "\t\t\t\t<Roughness>Medium Rough</Roughness>\n"
                "\t\t\t\t<WaterVaporDiffusionResistanceFactor>23.000000</WaterVaporDiffusionResistanceFactor>\n"
                "\t\t\t\t<MoistureStorageFunction>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.000000</x>\n"
                "\t\t\t\t\t\t<y>0.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.300000</x>\n"
                "\t\t\t\t\t\t<y>4.300000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.400000</x>\n"
                "\t\t\t\t\t\t<y>5.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.500000</x>\n"
                "\t\t\t\t\t\t<y>6.100000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.600000</x>\n"
                "\t\t\t\t\t\t<y>7.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.700000</x>\n"
                "\t\t\t\t\t\t<y>8.600000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.800000</x>\n"
                "\t\t\t\t\t\t<y>10.500000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.900000</x>\n"
                "\t\t\t\t\t\t<y>13.900000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.950000</x>\n"
                "\t\t\t\t\t\t<y>18.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.995000</x>\n"
                "\t\t\t\t\t\t<y>46.600000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999000</x>\n"
                "\t\t\t\t\t\t<y>83.500000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999500</x>\n"
                "\t\t\t\t\t\t<y>105.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999900</x>\n"
                "\t\t\t\t\t\t<y>167.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>1.000000</x>\n"
                "\t\t\t\t\t\t<y>405.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t</MoistureStorageFunction>\n"
                "\t\t\t</HygroThermal>\n"
                "\t\t\t<Optical>\n"
                "\t\t\t\t<Integrated>\n"
                "\t\t\t\t\t<Infrared>\n"
                "\t\t\t\t\t\t<Emissivity-Front>0.9</Emissivity-Front>\n"
                "\t\t\t\t\t\t<Emissivity-Back>0.9</Emissivity-Back>\n"
                "\t\t\t\t\t</Infrared>\n"
                "\t\t\t\t</Integrated>\n"
                "\t\t\t</Optical>\n"
                "\t\t</Solid>\n"
                "\t</Material>\n"};
    }

    std::string material2()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>a0eaba24-c61f-11ea-87d0-0242ac130003</UUID>\n"
                "\t\t<Name>Test Material 2</Name>\n"
                "\t\t<Protected>true</Protected>\n"
                "\t\t<Color>0xBAA7A7</Color>\n"
                "\t\t<Solid>\n"
                "\t\t\t<HygroThermal>\n"
                "\t\t\t\t<BulkDensity>1330.000000</BulkDensity>\n"
                "\t\t\t\t<Porosity>0.500000</Porosity>\n"
                "\t\t\t\t<SpecificHeatCapacityDry>850.000000</SpecificHeatCapacityDry>\n"
                "\t\t\t\t<ThermalConductivityDry>0.870000</ThermalConductivityDry>\n"
                "\t\t\t\t<Emissivity>0.9</Emissivity>\n"
                "\t\t\t\t<WaterVaporDiffusionResistanceFactor>23.000000</WaterVaporDiffusionResistanceFactor>\n"
                "\t\t\t\t<MoistureStorageFunction>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.000000</x>\n"
                "\t\t\t\t\t\t<y>0.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.300000</x>\n"
                "\t\t\t\t\t\t<y>4.300000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.400000</x>\n"
                "\t\t\t\t\t\t<y>5.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.500000</x>\n"
                "\t\t\t\t\t\t<y>6.100000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.600000</x>\n"
                "\t\t\t\t\t\t<y>7.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.700000</x>\n"
                "\t\t\t\t\t\t<y>8.600000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.800000</x>\n"
                "\t\t\t\t\t\t<y>10.500000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.900000</x>\n"
                "\t\t\t\t\t\t<y>13.900000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.950000</x>\n"
                "\t\t\t\t\t\t<y>18.200000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.995000</x>\n"
                "\t\t\t\t\t\t<y>46.600000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999000</x>\n"
                "\t\t\t\t\t\t<y>83.500000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999500</x>\n"
                "\t\t\t\t\t\t<y>105.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>0.999900</x>\n"
                "\t\t\t\t\t\t<y>167.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t\t<TableValue>\n"
                "\t\t\t\t\t\t<x>1.000000</x>\n"
                "\t\t\t\t\t\t<y>405.000000</y>\n"
                "\t\t\t\t\t</TableValue>\n"
                "\t\t\t\t</MoistureStorageFunction>\n"
                "\t\t\t</HygroThermal>\n"
                "\t\t\t<Optical>\n"
                "\t\t\t\t<Integrated>\n"
                "\t\t\t\t\t<Infrared>\n"
                "\t\t\t\t\t\t<Emissivity-Front>0.9</Emissivity-Front>\n"
                "\t\t\t\t\t\t<Emissivity-Back>0.9</Emissivity-Back>\n"
                "\t\t\t\t\t</Infrared>\n"
                "\t\t\t\t</Integrated>\n"
                "\t\t\t</Optical>\n"
                "\t\t</Solid>\n"
                "\t</Material>\n"};
    }

    std::string shade1()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>08eeb0cc-bb61-4a45-8746-27d450868de6</UUID>\n"
                "\t\t<Name>Test Shade</Name>\n"
                "\t\t<Protected>true</Protected>\n"
                "\t\t<Color>0x00FFF0</Color>\n"
                "\t\t<Solid>\n"
                "\t\t\t<HygroThermal>\n"
                "\t\t\t\t<ThermalConductivityDry>1.2</ThermalConductivityDry>\n"
                "\t\t\t</HygroThermal>\n"
                "\t\t\t<Optical>\n"
                "\t\t\t\t<Integrated>\n"
                "\t\t\t\t\t<Infrared>\n"
                "\t\t\t\t\t\t<Transmittance>0</Transmittance>\n"
                "\t\t\t\t\t\t<Emissivity-Front>0.9</Emissivity-Front>\n"
                "\t\t\t\t\t\t<Emissivity-Back>0.9</Emissivity-Back>\n"
                "\t\t\t\t\t</Infrared>\n"
                "\t\t\t\t\t<Solar>\n"
                "\t\t\t\t\t\t<Direct>\n"
                "\t\t\t\t\t\t\t<Front>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.1</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.3</Reflectance>\n"
                "\t\t\t\t\t\t\t</Front>\n"
                "\t\t\t\t\t\t\t<Back>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.2</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.4</Reflectance>\n"
                "\t\t\t\t\t\t\t</Back>\n"
                "\t\t\t\t\t\t</Direct>\n"
                "\t\t\t\t\t\t<Diffuse>\n"
                "\t\t\t\t\t\t\t<Front>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.11</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.33</Reflectance>\n"
                "\t\t\t\t\t\t\t</Front>\n"
                "\t\t\t\t\t\t\t<Back>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.22</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.44</Reflectance>\n"
                "\t\t\t\t\t\t\t</Back>\n"
                "\t\t\t\t\t\t</Diffuse>\n"
                "\t\t\t\t\t</Solar>\n"
                "\t\t\t\t\t<Visible>\n"
                "\t\t\t\t\t\t<Direct>\n"
                "\t\t\t\t\t\t\t<Front>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.2</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.4</Reflectance>\n"
                "\t\t\t\t\t\t\t</Front>\n"
                "\t\t\t\t\t\t\t<Back>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.3</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.5</Reflectance>\n"
                "\t\t\t\t\t\t\t</Back>\n"
                "\t\t\t\t\t\t</Direct>\n"
                "\t\t\t\t\t\t<Diffuse>\n"
                "\t\t\t\t\t\t\t<Front>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.22</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.44</Reflectance>\n"
                "\t\t\t\t\t\t\t</Front>\n"
                "\t\t\t\t\t\t\t<Back>\n"
                "\t\t\t\t\t\t\t\t<Transmittance>0.33</Transmittance>\n"
                "\t\t\t\t\t\t\t\t<Reflectance>0.55</Reflectance>\n"
                "\t\t\t\t\t\t\t</Back>\n"
                "\t\t\t\t\t\t</Diffuse>\n"
                "\t\t\t\t\t</Visible>\n"
                "\t\t\t\t</Integrated>\n"
                "\t\t\t</Optical>\n"
                "\t\t</Solid>\n"
                "\t</Material>\n"};
    }

    std::string enclosure1()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>c28a0554-3148-4a57-bb22-d93852b1604e</UUID>\n"
                "\t\t<Name>Radiation Enclosure</Name>\n"
                "\t\t<Protected>true</Protected>\n"
                "\t\t<Color>0xFFFF00</Color>\n"
                "\t\t<RadiationEnclosure>\n"
                "\t\t\t<EmissivityDefault>1.0</EmissivityDefault>\n"
                "\t\t</RadiationEnclosure>\n"
                "\t</Material>\n"};
    }

    std::string cavity1()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>6519c230-388d-11ea-a137-2e728ce88125</UUID>\n"
                "\t\t<Name>Frame Cavity 1</Name>\n"
                "\t\t<Protected>false</Protected>\n"
                "\t\t<Color>0x00FF00</Color>\n"
                "\t\t<Cavity>\n"
                "\t\t\t<CavityStandard>CEN</CavityStandard>\n"
                "\t\t\t<Gas>Air</Gas>\n"
                "\t\t\t<EmissivitySide1>0.9</EmissivitySide1>\n"
                "\t\t\t<EmissivitySide2>0.84</EmissivitySide2>\n"
                "\t\t</Cavity>\n"
                "\t</Material>\n"};
    }
    std::string cavity2()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>ac9cd31e-6419-4704-b659-7ec5a05bd998</UUID>\n"
                "\t\t<Name>Frame Cavity 2</Name>\n"
                "\t\t<Protected>false</Protected>\n"
                "\t\t<Color>0x00FF00</Color>\n"
                "\t\t<Cavity>\n"
                "\t\t\t<CavityStandard>CEN</CavityStandard>\n"
                "\t\t\t<Gas>Argon</Gas>\n"
                "\t\t\t<EmissivitySide1>0.84</EmissivitySide1>\n"
                "\t\t\t<EmissivitySide2>0.84</EmissivitySide2>\n"
                "\t\t</Cavity>\n"
                "\t</Material>\n"};
    }

    std::string emptyMoisture1()
    {
        return {"\t<Material>\n"
                "\t\t<UUID>75716f29-288a-4eb0-acab-21faa5bd5807</UUID>\n"
                "\t\t<Name>Test Material Empty Moisture 1</Name>\n"
                "\t\t<Protected>true</Protected>\n"
                "\t\t<Color>0xBAA7A7</Color>\n"
                "\t\t<Solid>\n"
                "\t\t\t<HygroThermal>\n"
                "\t\t\t\t<BulkDensity>1330.000000</BulkDensity>\n"
                "\t\t\t\t<Porosity>0.500000</Porosity>\n"
                "\t\t\t\t<SpecificHeatCapacityDry>850.000000</SpecificHeatCapacityDry>\n"
                "\t\t\t\t<ThermalConductivityDry>0.870000</ThermalConductivityDry>\n"
                "\t\t\t\t<WaterVaporDiffusionResistanceFactor>23.000000</WaterVaporDiffusionResistanceFactor>\n"
                "\t\t\t\t<MoistureStorageFunction/>\n"
                "\t\t\t</HygroThermal>\n"
                "\t\t\t<Optical>\n"
                "\t\t\t\t<Integrated>\n"
                "\t\t\t\t\t<Infrared>\n"
                "\t\t\t\t\t\t<Emissivity-Front>0.9</Emissivity-Front>\n"
                "\t\t\t\t\t\t<Emissivity-Back>0.9</Emissivity-Back>\n"
                "\t\t\t\t\t</Infrared>\n"
                "\t\t\t\t</Integrated>\n"
                "\t\t\t</Optical>\n"
                "\t\t</Solid>\n"
                "\t</Material>\n"};
    }
}   // namespace TestMaterial
